//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Apr 14 13:36:44 2026 by ROOT version 6.38.04)
//      from the StreamerInfo in file /home/filippo/raw_to_digi/raw_data/run1000779/run1000779.root
//////////////////////////////////////////////////////////


#ifndef edm__Wrapper_FEDRawDataCollection__h
#define edm__Wrapper_FEDRawDataCollection__h
class FEDRawDataCollection;
namespace edm {
template <typename T0> class Wrapper;
template <> class Wrapper<FEDRawDataCollection>;
} // end of namespace.

#include "Rtypes.h"
#include "FEDRawDataCollection.h"
#include "edm__WrapperBase.h"

namespace edm {
template <typename T0> class Wrapper;
template <> class Wrapper<FEDRawDataCollection> : public edm::WrapperBase {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        present;     //
   FEDRawDataCollection obj;         //

   Wrapper();
   Wrapper(Wrapper && ) = default;
   Wrapper &operator=(const Wrapper & );
   Wrapper(const Wrapper & );
   virtual ~Wrapper();

   ClassDef(Wrapper,4); // Generated by MakeProject.
};
} // namespace
#endif
