//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Apr 14 13:36:44 2026 by ROOT version 6.38.04)
//      from the StreamerInfo in file /home/filippo/raw_to_digi/raw_data/run1000779/run1000779.root
//////////////////////////////////////////////////////////


#ifndef FEDRawData_h
#define FEDRawData_h
class FEDRawData;

#include "Rtypes.h"
#include "Riostream.h"
#include <vector>

class FEDRawData {

public:
// Nested classes declaration.

public:
// Data Members.
   std::vector<unsigned char> data_;       //

   FEDRawData();
   FEDRawData(FEDRawData && ) = default;
   FEDRawData &operator=(const FEDRawData & );
   FEDRawData(const FEDRawData & );
   virtual ~FEDRawData();

   ClassDef(FEDRawData,11); // Generated by MakeProject.
};
#endif
